version: "3"

services:
  docker-mariaDB:
    container_name: docker-groupDB
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: planit_group
      MYSQL_USER: planit
      MYSQL_PASSWORD: planit1234
    ports:
      - 8001:3306

  docker-spring:
    container_name: docker-group
    image: dlaudghtn/group-service:v1
    restart: on-failure
    depends_on:
      - docker-mariaDB
    ports:
      - 9003:9003
