spring:
  profiles: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://group-db-server-service.default.svc.cluster.local:3306/planit_group?useUnicode=true&charaterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: planit
    password: planit1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    show-sql: true
    hibernate:
      ddl-auto: update