# Configure 'Deployment' of mysql server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-db
  labels:
    app: group-db
    tier: database
spec:
  selector: # mysql Pod Should contain same labels
    matchLabels:
      app: group-db
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: group-db
        tier: database
    spec:
      containers:
        - image: shoon2430/mariadb:v1 # image from docker-hub
          # args:
          #   - "--ignore-db-dir=lost+found" # Workaround for https://github.com/docker-library/mysql/issues/186
          name: group-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: planit
            - name: MYSQL_PASSWORD
              value: planit1234
            - name: MYSQL_DATABASE
              value: planit_group
          ports:
            - containerPort: 3306
              name: group-db
          volumeMounts: # Mounting voulume obtained from Persistent Volume Claim
            - name: group-db-persistent-storage
              mountPath: /var/lib/mysql #This is the path in the container on which the mounting will take place.
      volumes:
        - name: group-db-persistent-storage # Obtaining 'vloume' from PVC
          persistentVolumeClaim:
            claimName: group-db-pv-claim
